---
# tasks file for junaid18183.jenkins
   - name: Add Jenkins group(gid=600)
     group: name=jenkins state=present gid=600

   - name: Add user Jenkins (uid=600)
     user: name=jenkins state=present uid=600 shell=/bin/false home=/var/lib/jenkins createhome=yes comment='Jenkins Continuous Build server' group=jenkins

   - name: Install Jenkins and Java packages
     yum: pkg={{ item }}  state=present
     with_items:
      - jenkins
      - java-1.7.0-openjdk.x86_64

   - name: Generate the RSA key for Jenkins user
     user: name=jenkins generate_ssh_key=yes ssh_key_type=rsa

   - name: Add Jenkins in chkconfig
     service: name=jenkins  enabled=yes

   - name: Start Jenkins service
     service: name=jenkins state=started
